### ISSUE TITLE
System Reports app is a mess

### ISSUE THREAD

**Issue by BillDietrich** [linuxmint/mintreport#42]
mintreport 1.0.6

* No man page

* No CLI arguments such as --help or --version

* No About menu item in the GUI

* If you see a report listed and just want to delete it, first you have to click on the report title in the list, then wait 10-30 seconds while the app gathers all the crash reports etc, before you can then click on the Delete button to delete the report.  Please make a much faster way to delete.

**Comment by xenopeek** [comment]
Current version of mintreport is 1.1.5. It doesn't support any CLI arguments so a man page or --help argument would be pointless. The GUI has a Help > About menu item so that is implemented. I can't say whether crash reports are faster to delete in this version as I haven't had any yet. Closing this for now considering it's reported for an older version.

Are there CLI arguments you think would be useful for mintreport besides --help and --version? If so I suggest to make a new feature request issue for that.

If deleting of crash reports is still slow I think that also is best reported in a separate issue.
